- name: Ensure /project/ exists
  file:
    path: /project/
    state: directory
- copy:
    src: ./requirements.txt
    dest: /project/
- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
- name: Install the latest version of pip
  yum:
    name: python2-pip
    state: latest
    update_cache: yes
    disable_gpg_check: yes
- name: Make sure python requirements are met
  pip:
    requirements: /project/requirements.txt
    extra_args: --disable-pip-version-check
- name: Ensure /project/ exists
  file:
    path: /project/
    state: directory
- copy:
    src: ./testapp/
    dest: /project/
- shell: python /project/manage.py migrate
  args:
    chdir: /project
